data<-data.frame()
data<-read.table("household_power_consumption.txt", sep=";", dec=".", header=TRUE, na="?", colClasses=(c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")))
smalldata<-data.frame()
smalldata<-subset(data, data$Date=="1/2/2007" | data$Date=="2/2/2007")
smalldata<-transform(smalldata, DateTime=paste(Date, Time, sep=" "))
newsmalldata<-data.frame()
newsmalldata<-smalldata[,!(names(smalldata) %in% c("Date", "Time"))]
newsmalldata$DateTime<-strptime(newsmalldata$DateTime, "%d/%m/%Y %H:%M:%S")
plot(newsmalldata$DateTime, newsmalldata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(newsmalldata$DateTime, newsmalldata$Sub_metering_2, type="l", col="red")
lines(newsmalldata$DateTime, newsmalldata$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd=1, cex=0.6)
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()
